version: "3.5"
services:
  metro-app:
    image: metro:latest
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - metro-db

  metro-db:
    image: postgres:9.4
    ports:
      - 5432:5432
    volumes:
      - "metro-data-db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=metro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stevica

volumes:
  metro-data-db: